DROP TABLE ANYONE.EXECUTIONS;
CREATE TABLE ANYONE.EXECUTIONS(OBJECT_ID VARCHAR(40) NOT NULL PRIMARY KEY, SYMBOL VARCHAR(30), SIDE VARCHAR(20), QUANTITY DOUBLE, PRICE DOUBLE,
	ORDER_ID VARCHAR(40), PARENT_ID VARCHAR(40), STRATEGY_ID VARCHAR(40), EXEC_ID VARCHAR(40), MODIFIED TIMESTAMP, CREATED TIMESTAMP, SEQ_ID VARCHAR(40), SERVER_ID VARCHAR(40));

DROP TABLE ANYONE.ACTIVE_CHILD_ORDERS;
CREATE TABLE ANYONE.ACTIVE_CHILD_ORDERS(OBJECT_ID VARCHAR(40) NOT NULL PRIMARY KEY, SYMBOL VARCHAR(30), SIDE VARCHAR(20), QUANTITY DOUBLE, PRICE DOUBLE,
	CUM_QTY DOUBLE, AVG_PX DOUBLE, ORDER_TYPE VARCHAR(20), ORD_STATUS VARCHAR(20), PARENT_ID VARCHAR(40), STRATEGY_ID VARCHAR(40), 
	MODIFIED TIMESTAMP, CREATED TIMESTAMP, SEQ_ID VARCHAR(40), CLORDER_ID VARCHAR(40), SERVER_ID VARCHAR(40));

DROP TABLE ANYONE.CHILD_ORDER_AUDIT;
CREATE TABLE ANYONE.CHILD_ORDER_AUDIT(AUDIT_ID VARCHAR(40) NOT NULL PRIMARY KEY,OBJECT_ID VARCHAR(40), EXEC_TYPE VARCHAR(20), SYMBOL VARCHAR(30), SIDE VARCHAR(20), QUANTITY DOUBLE, PRICE DOUBLE,
	CUM_QTY DOUBLE, AVG_PX DOUBLE, ORDER_TYPE VARCHAR(20), ORD_STATUS VARCHAR(20), PARENT_ID VARCHAR(40), STRATEGY_ID VARCHAR(40), 
	MODIFIED TIMESTAMP, CREATED TIMESTAMP, SEQ_ID VARCHAR(40), CLORDER_ID VARCHAR(40), SERVER_ID VARCHAR(40));

DROP TABLE ANYONE.STRATEGIES;
CREATE TABLE ANYONE.STRATEGIES(OBJECT_ID VARCHAR(40), LINE_NO INTEGER, TIME_STAMP TIMESTAMP, XML_TEXT VARCHAR(4096), 
	CONSTRAINT ST_PRIMARY_KEY PRIMARY KEY (OBJECT_ID, LINE_NO), SERVER_ID VARCHAR(40));
CREATE INDEX ST_INDEX ON ANYONE.STRATEGIES (OBJECT_ID);
